- name: "Initialize Kubernetes Master"
  kubeadm_init: "{{ init_info }}"
  register: init_status
  ignore_errors: true


- name: "Configure Client on Matser"
  include: "client.yml"

- name: "Create Intermidate Token"
  kubeadm_token:
          description: "good"
          action: "create"
  register: token_status
  ignore_errors: true

- debug:
        var: token_status

- name: "Include 'Recreation Token' Tasks File"
  include: "recreate_token.yml"
  when: not token_status.changed

- blockinfile:
        block: "{{ token_status }}"
        path: "token/token.json"
        create: True
  delegate_to: localhost

- name: "Configure Container Network Interface"
  include: "CNInterface/{{ container_network_interface }}.yml"
