- name: "Check Slave Already Joined to Master or NOT"
  command: systemctl status kubelet
  ignore_errors: true
  register: kubelet_status

- name: "Configure Slave"
  include: "slave.yml"
  when: kubelet_status.failed
  vars:
          bridging_file_path_for_k8s: "/etc/sysctl.d/k8s.conf"

#- block:
#          - name: "Check Slave Already Joined to Master or NOT"
#            command: systemctl status kubelet
# rescue:
#         - name: "Configure Slave"
#           include: "slave.yml"
#           vars:
#                   bridging_file_path_for_k8s: "/etc/sysctl.d/k8s.conf"
