- name: "Task Block For Installation of Docker"
  block:
          - name: "Include Task File to install docker"
            include: "type_1.yml"
  rescue:
          - name: "Include Repo Creation Task for docker"
            include: "repo_creation.yml"
            when: docker_pkg_status.rc == 1

- name: "Task Block For Docker Configuration" 
  block:
          - name: "Start and Enable Docker"
            service:
                    name: "docker"
                    state: started
                    enabled: True
  rescue:
          - name: "Clear Caches"
            include: "{{ ansible_facts.distribution }}/clear_caches.yml"
  always:
          - name: "Change Driver 'cgroupfs' to 'systemd' for docker"
            copy:
                    src: "daemon.json"
                    dest: "/etc/docker/daemon.json"
            register: docker_conf_status
          - name: "Reload Docker Service If any changes occur"
            service:
                    name: "docker"
                    state: restarted
                    enabled: True
            when: docker_conf_status.changed
